[package]
name = "VintageModManager"
version = "0.2.0"
edition = "2021"
authors = [
    "Mikkel M.H Pedersen <@mikkel.helding@gmail.com>"
]
license = "MIT"


[dependencies]

reqwest = { version = "0.12.12", features = ["json"]}
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
tokio = { version = "1.43.0", features = ["full"] }

bytes = "1.10.0"
thiserror = "2.0.11"
imgui = "0.12.0"

api = { path = "libraries/api" }
utils = { path = "libraries/utils" }
bincode = "1.3.3"
clap = { version = "4.5.28", features = ["derive"] }

