[package]
name = "VintageModManager"
version = "0.1.0"
edition = "2021"

[dependencies]

reqwest = { version = "0.12.12", features = ["json"]}
serde = { version = "1.0.119", features = ["derive"] }
serde_json = "1.0.61"
serde_derive = "1.0.119"
tokio = { version = "1.0.2", features = ["full"] }
base64 = "0.22.1"
chrono = "0.4.39"
colored = "3.0.0"
bytes = "1.10.0"
thiserror = "2.0.11"
imgui = "0.12.0"
