[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
chrono = "0.4.39"
colored = "3.0.0"
thiserror = "2.0.11"
tokio = "1.43.0"
bytes = "1.10.0"
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }


