name: formatter

on: [push]

jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Run cargo fmt
      run: cargo fmt --all -- --check
